FROM ubuntu:24.04 AS builder

WORKDIR /workspace

ENV DEBIAN_FRONTEND=noninteractive

ENV PYTHON_VERSION=3.13.12

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    g++ \
    gnupg \
    libatomic1 \
    libegl1 \
    libbz2-dev \
    libffi-dev \
    libgl1 \
    libgomp1 \
    liblzma-dev \
    libreadline-dev \
    libsqlite3-dev \
    lsb-release \
    libssl-dev \
    libx11-xcb1 \
    make \
    software-properties-common \
    sqlite3 \
    tzdata \
    unzip \
    wget \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

######################## Python installation #########################

# Download Python source code from official site and build it
RUN wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz && \
    tar -zxvf Python-$PYTHON_VERSION.tgz && \
    cd Python-$PYTHON_VERSION && \
    ./configure --enable-optimizations && make && make install && \
    cd .. && \
    rm Python-$PYTHON_VERSION.tgz && \
    rm -r Python-$PYTHON_VERSION

RUN wget https://bootstrap.pypa.io/get-pip.py -O get-pip.py

#################### Create Virtual Environment ######################

ENV VIRTUAL_ENV=/workspace/venv
RUN python3.13 -m venv $VIRTUAL_ENV

# by adding the venv to the search path, we avoid activating it in each command
# see https://pythonspeed.com/articles/activate-virtualenv-dockerfile/
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# install pip into venv
RUN python get-pip.py && python -m pip install --upgrade pip

######## Install PyTorch and packages that depend on PyTorch #########

# these packages are dependencies of the other packages but not listed in their requirements
# therefore, they have to be installed manually
RUN python -m pip install tensorboard yapf wheel packaging
RUN python -m pip install torch==2.10.0 torchvision==0.25.0 torchaudio==2.10.0 --index-url https://download.pytorch.org/whl/cpu
RUN python -m pip install torch-scatter torch-cluster -f https://data.pyg.org/whl/torch-2.10.0+cpu.html
RUN python -m pip install --no-build-isolation "git+https://github.com/facebookresearch/pytorch3d.git@stable"
RUN python -m pip install spconv

# ######################## Open3D build #################################
RUN python -m pip install open3d

# uninstall build dependencies from virtual environment again
RUN python -m pip uninstall -y yapf wheel packaging
    
####################################################################
######################### Target Image #############################
####################################################################

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

ENV PYTHON_VERSION=3.13.12

WORKDIR /workspace

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    g++ \
    gnupg \
    libatomic1 \
    libegl1 \
    libbz2-dev \
    libffi-dev \
    libgl1 \
    libgomp1 \
    liblzma-dev \
    libreadline-dev \
    libsqlite3-dev \
    lsb-release \
    libssl-dev \
    libx11-xcb1 \
    make \
    software-properties-common \
    sqlite3 \
    tzdata \
    unzip \
    wget \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

######################## Rclone installation ########################

RUN curl https://rclone.org/install.sh | bash

#################### Copy Virtual Environment ######################

ENV VIRTUAL_ENV=/workspace/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY --from=builder /workspace/venv /workspace/venv

# copy additional libs that are needed by Open3D
COPY --from=builder /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libGL.so
COPY --from=builder /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/x86_64-linux-gnu/libGL.so.1
COPY --from=builder /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
COPY --from=builder /usr/lib/x86_64-linux-gnu/libGLX.so.0 /usr/lib/x86_64-linux-gnu/libGLX.so.0

# copy Python installation to avoid building Python twice
COPY --from=builder /usr/local/bin/python3.13 /usr/local/bin/python3.13
COPY --from=builder /usr/local/lib/python3.13 /usr/local/lib/python3.13
COPY --from=builder /usr/local/include/python3.13 /usr/local/include/python3.13

RUN mkdir pointtorch
ADD . pointtorch
RUN python -m pip install ./pointtorch[dev,docs]
